import { Character, Quest, BossRaid, ShopItem } from '@/types/game';
import { getRequiredXP, getFeatDescription } from './rpg-engine';

export const mockCharacter: Character = {
  id: "hunter-demo-01",
  userId: "user-demo",
  name: "Jin-Woo",
  title: "Shadow Monarch Apprentice",
  level: 3,
  currentXp: 185,
  requiredXp: getRequiredXP(3),
  gold: 140,
  streakCount: 5,
  lastActiveDate: new Date().toISOString(),
  sacrificesThisMonth: 0,
  attributes: {
    STR: {
      level: 4,
      currentXp: 75,
      requiredXp: getRequiredXP(4),
      featDescription: getFeatDescription('STR', 4),
    },
    INT: {
      level: 6,
      currentXp: 110,
      requiredXp: getRequiredXP(6),
      featDescription: getFeatDescription('INT', 6),
    },
    VIT: {
      level: 3,
      currentXp: 40,
      requiredXp: getRequiredXP(3),
      featDescription: getFeatDescription('VIT', 3),
    },
    AGI: {
      level: 4,
      currentXp: 60,
      requiredXp: getRequiredXP(4),
      featDescription: getFeatDescription('AGI', 4),
    },
    CHA: {
      level: 2,
      currentXp: 20,
      requiredXp: getRequiredXP(2),
      featDescription: getFeatDescription('CHA', 2),
    },
  },
};

export const mockQuests: Quest[] = [
  {
    id: "q-1",
    title: "Morning Hydration Rite",
    description: "Drink 500ml pure water upon waking to cleanse bodily toxins.",
    category: "VIT",
    rank: "E",
    xpReward: 15,
    goldReward: 5,
    status: "PENDING",
    isDaily: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "q-2",
    title: "Deep Work Coding Block",
    description: "Implement database connection and API routes without tab-switching.",
    category: "INT",
    rank: "B",
    xpReward: 75,
    goldReward: 35,
    status: "PENDING",
    isDaily: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "q-3",
    title: "Hunter's Physical Conditioning",
    description: "50 push-ups, 50 squats, 2km jog to maintain battle readiness.",
    category: "STR",
    rank: "C",
    xpReward: 40,
    goldReward: 20,
    status: "PENDING",
    isDaily: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "q-4",
    title: "Inbox Zero Sweep",
    description: "Purge all unread notifications and organize project tasks.",
    category: "AGI",
    rank: "D",
    xpReward: 25,
    goldReward: 10,
    status: "COMPLETED",
    isDaily: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "q-5",
    title: "Guild Synchronization Standup",
    description: "Deliver crisp 5-minute progress report to the party.",
    category: "CHA",
    rank: "C",
    xpReward: 40,
    goldReward: 20,
    status: "PENDING",
    isDaily: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockBoss: BossRaid = {
  id: "boss-01",
  name: "Malakor the Sloth",
  title: "Lord of Distraction & Procrastination",
  maxHp: 3000,
  currentHp: 2180,
  deadline: "Sunday 23:59 UTC",
  rewardGold: 250,
  rewardTitle: "Demon Slayer of Aetheria",
  defeated: false,
};

export const mockShopItems: ShopItem[] = [
  {
    id: "item-1",
    name: "Scroll of Focus",
    description: "Ancient papyrus granting +10% INT XP on all coding and study bounties.",
    cost: 80,
    type: "RELIC",
    statBoost: "+10% INT XP",
    iconSlug: "scroll",
  },
  {
    id: "item-2",
    name: "Aegis Streak Shield",
    description: "Golden talisman that automatically freezes and preserves your streak if you miss a day.",
    cost: 150,
    type: "RELIC",
    statBoost: "Streak Freeze (1x)",
    iconSlug: "shield",
  },
  {
    id: "item-3",
    name: "XP Surge Elixir",
    description: "Brewed potion granting 2x XP multiplier for your next 3 completed bounties.",
    cost: 120,
    type: "RELIC",
    statBoost: "2x XP (3 charges)",
    iconSlug: "potion",
  },
  {
    id: "item-4",
    name: "1-Hour Gaming Pass",
    description: "Real-world permission token: 60 minutes of completely guilt-free video game time.",
    cost: 100,
    type: "REAL_WORLD",
    statBoost: "Real-Life Reward",
    iconSlug: "gamepad",
  },
  {
    id: "item-5",
    name: "Guilt-Free Cheat Meal",
    description: "Real-world permission token: Order pizza, burgers, or sushi without regret.",
    cost: 300,
    type: "REAL_WORLD",
    statBoost: "Real-Life Reward",
    iconSlug: "pizza",
  },
  {
    id: "item-6",
    name: "Sleep-In / Day-Off Pass",
    description: "Real-world permission token: Turn off the morning alarm and rest deeply.",
    cost: 400,
    type: "REAL_WORLD",
    statBoost: "Real-Life Reward",
    iconSlug: "moon",
  },
];
